- app/Http/Controllers/CuentasCobrarController.php
- app/Http/Controllers/CuentasPagarController.php
- public/js/sgt/cxc/cxc.js
- public/js/sgt/cxp/cxp.js
- resources/views/cuentas_cobrar/cobranza_cliente.blade.php
- resources/views/cuentas_pagar/pagos_v2.blade.php
- resources/views/planeacion/edit.blade.php
- routes/web.php
> Cuentas x pagar

- app/Http/Controllers/CuentasPagarController.php
- public/js/sgt/cxp/cxp.js
Se agregó misma solucion en CXP, la finalidad es tomar en cuenta arreglos con dimensiones mayores a 100
> Convertir Data en JSON en CxP

- resources/views/layouts/sidebar.blade.php
Se modifica el codigo para configurar el acceso a reportes de forma independiente
> Modificacion permisos a reporteria

- app/Http/Controllers/ReporteriaController.php
- public/js/sgt/reporteria/viajes_list.js
- resources/views/reporteria/asignaciones/excel.blade.php
- resources/views/reporteria/asignaciones/index.blade.php
- resources/views/reporteria/asignaciones/pdf.blade.php
Cambio de diseño y funcionalidad
> Cambios Reportes viaje

- app/Events/EnvioCorreoCoordenadasEvent.php
- app/Http/Controllers/CoordenadasController.php
- app/Http/Controllers/CotizacionesController.php
- app/Listeners/EnviarCorreoCoordenadasListener.php
- app/Mail/CorreoCoordenadasMail.php
- app/Models/Coordenadas.php
- app/Providers/EventServiceProvider.php
- database/migrations/2025_04_16_225816_add_nuevas_columnas_patio_to_coordenadas_table.php
- public/assets/css/argon-dashboard.css
- public/js/sgt/cotizaciones/cotizaciones_list.js
- resources/views/coordendas/index.blade.php
- resources/views/coordendas/indexold.blade.php
- resources/views/cotizaciones/index.blade.php
- resources/views/dashboard.blade.php
- resources/views/emails/coordenadas.blade.php
- resources/views/emails/email-coordenadas.blade.php
- resources/views/layouts/sidebar.blade.php
- routes/web.php
modal compartir coordenadas email, whatsapp , correo enviado ok, link coordenadas arreglo por tipo de viaje ,
> cambiosAymer

- public/js/sgt/cotizaciones/cotizaciones_list.js
- routes/web.php
cambios errores prod cotizaciones
> solventacion

- app/Http/Controllers/CoordenadasController.php
- app/Http/Controllers/CotizacionesController.php
- app/Mail/CorreoCoordenadasMail.php
- app/Models/Coordenadas.php
- database/migrations/2025_04_24_201121_altercoordenadascolumntipo.php
- public/js/sgt/coordenadas/coordenadasver.js
- public/js/sgt/cotizaciones/cotizaciones_list.js
- resources/views/coordendas/index.blade.php
- resources/views/coordendas/indexold.blade.php
- resources/views/coordendas/vercoor.blade.php
- resources/views/cotizaciones/index.blade.php
- resources/views/dashboard.blade.php
- routes/web.php
Cambio mapas y coordenadas , preguntas y avance
> Presentacion

- app/Http/Controllers/CoordenadasController.php
- public/js/sgt/coordenadas/coordenadasver.js
- resources/views/coordendas/index.blade.php
- resources/views/coordendas/vercoor.blade.php
- resources/views/dashboard.blade.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/sidebar.blade.php
- routes/api.php
- routes/web.php
filtros en mapas y colocar varios contnedores en los marcadores
> mapas filtros

- app/Http/Controllers/ReporteriaController.php
- public/js/sgt/gastos/gastosContenedor.js
- public/js/sgt/reporteria/documento.js
- public/js/sgt/reporteria/gxp.js
- resources/views/reporteria/documentos/pdf.blade.php
- resources/views/reporteria/documentos/xlsx.blade.php
- resources/views/reporteria/gxp/pdf.blade.php
Se integra la opcion CIMA en reportes
> Reporte de documentos

- app/Traits/JimiGpsTrait.php
- config/services.php
> resorver-coordenadas

- app/Http/Controllers/ConboysController.php
- app/Http/Controllers/CoordenadasController.php
- app/Http/Controllers/PlaneacionController.php
- app/Http/Controllers/RastreoIntervalController.php
- public/js/sgt/coordenadas/coordenadasRastreoGPS.js
- public/js/sgt/coordenadas/coordenadasconboys.js
- resources/views/conboys/geocerca.blade.php
- resources/views/conboys/index.blade.php
- resources/views/conboys/mapa_comparacion.blade.php
- resources/views/conboys/ubicaciones.blade.php
- resources/views/mec/coordenadas/index.blade.php
- resources/views/scheduler/index.blade.php
correccion mapa comparacion y observaciones reunion martes
> mapas y bugs

- app/Http/Controllers/CoordenadasController.php
validacion de columna de actualizacion y actualizar cotizacion a finalizado
> validacion

- app/Http/Controllers/CoordenadasController.php
- public/js/sgt/coordenadas/coordenadasRastreoGPS.js
contenedores y convoys, rastreo principal
> validacion fechas

- resources/views/reporteria/cxc/index.blade.php
- resources/views/reporteria/cxp/index.blade.php
> index.cxp.reporteria, index.cxc.reporteria

- resources/views/reporteria/cxc/index.blade.php
- resources/views/reporteria/cxc/pdf.blade.php
- resources/views/reporteria/cxp/index.blade.php
> CXC, CXP REPORTERIA, se asigna el banco a empresa 8

- app/Http/Controllers/CoordenadasController.php
- app/Http/Controllers/GpsController.php
- public/js/sgt/coordenadas/coordenadasRastreo.js
cambio de colores marcadores, eliminacion
> marcadores

- app/Http/Controllers/CoordenadasController.php
- public/js/sgt/coordenadas/coordenadasRastreo.js
- resources/views/coordenadas/rastreoTab.blade.php
- resources/views/layouts/sidebar.blade.php
- resources/views/layouts/usuario_externo.blade.php
- resources/views/mec/coordenadas/rastrear.blade.php
Cambio a modulo rastreo a como esta SGT, se agrego por permiso los modulos y tabs
> rastro mec

- app/Console/Kernel.php
- app/Models/RastreoIntervals.php
> intervalo tiempo

- app/Http/Controllers/CoordenadasController.php
- app/Http/Controllers/GpsController.php
- public/js/sgt/coordenadas/coordenadasRastreo.js
- public/js/sgt/cotizaciones/cotizacion-documentacion.js
- resources/views/cotizaciones/externos/viajes_solicitados.blade.php
validacion si es cliente u empresa, revision y cambios en consultas
> cambios rastreo

- resources/views/cotizaciones/externos/datos_facturacion.blade.php
> cambios validacion
